version: "3.8"
services: 
    mysql_db:
        image: mysql:latest
        container_name: mysql_db
        hostname: mysql_db
        ports:
            - "3306:3306"
        volumes:
            - ./models/.mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=igtidyup
            - MYSQL_USER=arthur
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=root123